
import { connect, KeyPair, keyStores } from "near-api-js";

const MASTER_KEY = "ed25519:3D4YudUQRE39Lc4JHghuB5WM8kbgDDa34mnrEP5DdTApVH81af7e2dWgNPEaiQfdJnZq1CNPp5im4Rg5b733oiMP";
const MASTER_ACCOUNT = "node0";
const RPC_URL = "http://127.0.0.1:3030";

const NEW_KEYS = [
    { accountId: "mpc-node-0.node0", publicKey: "ed25519:69CETJnEyCTaQ7B3PxEWrsMWpoufayKFhHWN15HQ8smR" },
    { accountId: "mpc-node-1.node0", publicKey: "ed25519:93pcUSau23m7imF94gny2R9c8UDvGHGmiVFKr7j4pkjP" },
    { accountId: "mpc-node-2.node0", publicKey: "ed25519:5CJ4d6byRNacX5QNaASHGXmURtWE48xARnNGWAwKRiWg" }
];

async function main() {
    const keyStore = new keyStores.InMemoryKeyStore();
    await keyStore.setKey("localnet", MASTER_ACCOUNT, KeyPair.fromString(MASTER_KEY));

    const connection = await connect({
        networkId: "localnet",
        nodeUrl: RPC_URL,
        keyStore,
    });

    const masterAccount = await connection.account(MASTER_ACCOUNT);

    for (const { accountId, publicKey } of NEW_KEYS) {
        console.log(`Adding key ${publicKey} to ${accountId}...`);
        try {
            // We use the master account to execute the transaction on the sub-account?
            // No, we need to sign as the sub-account usually, OR as the creator if we can.
            // But we don't have the sub-account key (that's the problem).
            // Actually, we can delete the account and recreate it? No, that loses state.
            
            // Wait, node0 is the parent. Does it have FullAccess to subaccounts? No, not by default.
            
            // CHECK: Does node0 have a key for mpc-node-0.node0?
            // The logs said `ed25519:CTLd5chV...` exists. Do we have the private key for THAT?
            
            // If we don't have the private key for the existing key on the account, we are locked out.
            // UNLESS... we can use `node0` to delete and recreate the account.
            
            console.log(`Checking if ${accountId} exists...`);
            try {
                const account = await connection.account(accountId);
                await account.state();
                console.log("Account exists.");
                
                // We are locked out if we don't have the key.
                // Let's try to delete it using node0? Only if node0 is a beneficiary?
                // No.
                
                // OPTION: Recover the key from Secrets Manager that MATCHES the one on chain?
                // The on-chain key is `ed25519:CTLd5chV...`.
                // Do we have that secret key anywhere?
                // It was generated by `mpc-setup.ts` in a previous run.
                // If it wasn't saved to Secrets Manager (or was overwritten), it's lost.
                
                // CRITICAL: We might need to delete these accounts and recreate them.
                // Can `node0` delete `mpc-node-0.node0`? 
                // Only if `mpc-node-0.node0` signs the delete transaction.
                
                // Force delete? Not possible on protocol level.
                
                // WAIT! We replaced the genesis of the MPC nodes to match NEAR Base.
                // But the MPC nodes are using keys that they *think* they own.
                
                // Maybe we should update the MPC nodes to use the key that IS on the chain?
                // `ed25519:CTLd5chV...`
                
                // Do we have the secret key for `CTLd5chV...`?
                // If not, that account is dead.
                
                // BUT! This is a localnet. We control the validators.
                // We can't forge signatures though.
                
                // If we lost the key for `mpc-node-0.node0`, we must recreate the account.
                // But we can't delete it without the key.
                
                // This implies we need to use a NEW account ID for the MPC nodes?
                // e.g. `mpc-node-0-v2.node0`.
                
                // Let's try to create `mpc-node-0-v2.node0` and update the MPC node config to use that.
                
                const newAccountId = accountId.replace(".node0", "-v2.node0");
                console.log(`Creating replacement account ${newAccountId}...`);
                
                await masterAccount.createAccount(
                    newAccountId,
                    publicKey,
                    "10000000000000000000000000" // 10 NEAR
                );
                console.log("Success!");
                
            } catch (e) {
                console.error("Error:", e);
            }
        } catch (error) {
            console.error(`Failed to handle ${accountId}:`, error);
        }
    }
}

main();

